### ISSUE TITLE
Could not found ToolTip module

### ISSUE THREAD

**Issue by zfb132** [YJesus/Unhide#1]
@patrick-g2  I was trying to run the `unhideGui.py` after installing `tkinter`, but I got this error msg:  
```txt
Traceback (most recent call last):
  File "unhideGui.py", line 38, in <module>
    from ToolTip import *
ModuleNotFoundError: No module named 'ToolTip'
```
Did you forget to upload the `ToolTip.py` to this repo? Or Was It just an unfinished program?

**Comment by patrick-g2** [comment]
Ooops ! I have indeed forgotten to push the module.
I just fixed the oversight.
Just put the file in the same folder as unhideGui.
Thanks for the report.

**Comment by patrick-g2** [comment]
Alternatively, you can just comment the import.
The toll doesn't need it to work correctly.
