### ISSUE TITLE
unhide can't be run with suid permission

### ISSUE THREAD

**Issue by horschi** [YJesus/Unhide#7]
Hi,

I am trying to run unhide using suid permissions, but unhide checks for the actual user Id and not the effective user:

```
   if(getuid() != 0){
      die(unlog, "You must be root to run %s !", argv[0]) ;
   }
```

If geteuid() was used, I assume unhide could be run using the suid permissions. Would it be possible to change that?

cheers,
Christian

**Comment by patrick-g2** [comment]
Hi Christian,
It will surely works (short test seems to show it).
**But**, as unhide was written without SUID in mind, no effort were made to add protection against privilege escalation in the code.
Moreover I don't sea any valid reason for a standard user to execute unhide (remember: "Unhide is a forensic tool ..."). 
So I will not do this change in the official source code.

If configured to do so, sudoers can execute unhide without problem. It restricts authorized users to a trusted group. Well normally :).
Can you develop about your use case of a SUID unhide?

**You have been warned about the risks.**
But, if you really want to do it, you can do it by yourself in your own copy.
You need root privileges.
```
git clone https://github.com/YJesus/Unhide.git or get the zip-file.
change  getuid() with geteuid() in unhide-linux.c
gcc -Wall -O2 --static -pthread unhide-linux*.c unhide-output.c -o unhide-linux
put unhide-linux in the directory of your choice, where your user can read/execute (e.g. /bin)
go to that directory
sudo chown root:root unhide-linux
sudo chmod u+s unhide-linux
```
you're done.
Remember that, now, all users can execute unhide with root privilege with all the risks that come with it.

Regards,
Patrick.

**Comment by horschi** [comment]
Hi Patrick,
thanks for the swift response!

I am not a big fan of forking, because it means I also have to maintain it :-)

I think I will try to create a simple "launcher" app, that has suid permission and then launches unhide in a controlled way (without unhide having to parse command line args from a user - because they are only provide by my launcher app). I'm just not sure if the uid will change for that command call, or if somehow I have to change the uid. 

Edit: It seems I have to manually change the uid before calling unhide :-(

Edit2: setuid does the trick.

Let me know if you change you mind about the change.

best regards,
Christian

**Comment by patrick-g2** [comment]
Hi Christian,
> Let me know if you change you mind about the change.
I will try not to forget if it ever happens :)

Regards.
