### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by q2dg** [YJesus/Unhide#9]
Last commit was from two years ago...
Thanks!

**Comment by patrick-g2** [comment]
No, I'm still here.
But you have to understand that Unhide is a mature project (my first contribution was back in 2010!), and as such it no longer needs frequent updates. It's the famous  "if it works, don't change it". :)
However, if you have any suggestions for improvements or bug fixes, please do not hesitate to open an issue or create a PR.

**Comment by q2dg** [comment]
Thanks!
I'll close this issue, then.
Sorry for the inconvenience
